---
# tasks file for containers.yaml
- name: Criando o container Green
  file:
    name: "{{item}}"
    state: directory
  with_items:
    - /blue
    - /green

- name: Criando o container blue e green
  docker_container:
    name: "{{item.name}}"
    image: httpd
    state: started
    volumes:
      - "{{item.volume}}:/usr/local/apache2/htdocs/"
  with_items:
    - {name: green, volume: /green}
    - {name: blue, volume: /blue}
